inter_steps: 300
init_point: {
    x: 1.0,
    y: 2.0,
    z: -1.0
}
points: [0., 3., -1.,
        0., 2., -1.,
        -1., 1.5, -2.,
        -1.7, 0.5, -2.8,
        -1.7, -1., -0.5,
        0., -2.6, -0.6,
        -1., -1.2, -2.]
